<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>imga</name>
   <tag></tag>
   <elementGuidId>6dba3aba-2a7c-49c8-ab53-a8f7936c3fa9</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;OrangeHRM&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='branding']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9449cbb2-c296-4dbb-b9f8-2a147efdad9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/webres_62c611484a1667.42660422/themes/default/images/logo.png</value>
      <webElementGuid>14feb2c7-22b8-4619-8720-45d2bbafaf05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>283</value>
      <webElementGuid>d7842d4c-fba3-4b5e-a44e-42e5cb3b57c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>56</value>
      <webElementGuid>38d0f9ff-36e4-4d6a-8903-3479ae5bbb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>OrangeHRM</value>
      <webElementGuid>8b896df4-9ee8-4aa2-bb72-c472027a5718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;branding&quot;)/a[1]/img[1]</value>
      <webElementGuid>653ccede-2a0c-48b2-a71e-1e68551cf190</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='branding']/a/img</value>
      <webElementGuid>11075545-2e61-4f97-b690-a5bdbc8b0651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='OrangeHRM']</value>
      <webElementGuid>d7dae7c0-1994-48d4-ac88-8e71f23aedf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>09152ec5-99f9-423a-b4ed-810fb1972b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/webres_62c611484a1667.42660422/themes/default/images/logo.png' and @alt = 'OrangeHRM']</value>
      <webElementGuid>82b8a933-21f3-4b49-8175-d33df3e1151a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
