<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LOGIN Panel</name>
   <tag></tag>
   <elementGuidId>11aa89d5-8006-446e-90fe-19b3038fa0bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#logInPanelHeading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='logInPanelHeading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>61a26b82-f651-4ead-b00b-f0cf45881b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logInPanelHeading</value>
      <webElementGuid>13fc57d0-f317-4f2c-8565-92bae79e0948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGIN Panel</value>
      <webElementGuid>af46ccc7-c413-45b8-9fae-b950ad8a36dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logInPanelHeading&quot;)</value>
      <webElementGuid>cef849a9-e591-4f94-bbf9-74c19b26cebc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='logInPanelHeading']</value>
      <webElementGuid>30f1849a-3df6-4a5a-9fea-4c47762a623a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmLogin']/div</value>
      <webElementGuid>d7f7853b-42ae-40ab-911b-a5c20029c44a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='( Username : Admin | Password : admin123 )'])[1]/following::div[6]</value>
      <webElementGuid>283874c1-3fbb-432b-b307-12df7a6a95d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/preceding::div[1]</value>
      <webElementGuid>bd504860-b170-4820-864d-334cd0107060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::div[2]</value>
      <webElementGuid>0f63ff5b-e1d6-48a4-a051-0332b827ca8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LOGIN Panel']/parent::*</value>
      <webElementGuid>3cd36237-1d90-49e7-8e60-954bd557b8b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div</value>
      <webElementGuid>6e5ab726-9261-4ba8-9f0d-5000fc1dda7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'logInPanelHeading' and (text() = 'LOGIN Panel' or . = 'LOGIN Panel')]</value>
      <webElementGuid>41ba95a8-eb86-4d3a-8173-401232db45f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
